# Preprocessing

In [ ]:
# Read the input file
with open('/content/TRAINING20x50.txt') as f:
    lines = f.readlines()

In [ ]:
labels =[]
entries = []
count = 0
rlen=0

In [ ]:
for i in lines:
  if i.startswith('label'):
    sample_lab = i.split('\n')[0].split()[-1]
    labels.append(list(map(int, sample_lab.split(','))))
    count+=1
  elif i!='\n':
    entry = i.split('\n')[0].split()
    entry ="".join(entry)
    gg = [int(i) for i in entry]
    rlen=len(gg)
    entries.append(gg)
  else:
    continue

In [ ]:
rlen

21

In [ ]:
final_labels = []
for i, j in enumerate(labels):
    final_labels.append(j)

In [ ]:
import numpy as np
entries = np.array(entries)
final_labels = np.array(final_labels)
entries = entries.reshape(len(final_labels), -1)

In [ ]:
sz= len(entries[0])

In [ ]:
row_feat = entries[:, list(range(0, sz, rlen))]
col_feat = entries[:, [_ for _ in range(len(entries[0])) if _ not in list(range(0, sz, rlen))]]

In [ ]:
#split the dataset 
from sklearn.model_selection import train_test_split as tts
train_entries, val_entries, train_labels, val_labels = tts(entries, final_labels, test_size = 0.2,shuffle=False)

In [ ]:
train_row_entries, val_row_entries, train_row_labels, val_row_labels = tts(row_feat, final_labels[:, 1], test_size = 0.2,shuffle=False)

# Linear Regression

## For Row

In [ ]:
from sklearn.linear_model import LinearRegression
row_model = LinearRegression()
row_model.fit(train_row_entries, train_row_labels)

LinearRegression()

In [ ]:
#Predict the response for test dataset
y_pred_row = row_model.predict(val_row_entries)
y_pred_row

array([4.50000000e+01, 2.50000000e+01, 3.55271368e-14, 3.30000000e+01,
       1.40000000e+01, 7.00000000e+00, 4.60000000e+01, 2.20000000e+01,
       1.00000000e+01, 3.10000000e+01, 5.00000000e+00, 2.10000000e+01,
       1.00000000e+00, 8.00000000e+00, 2.60000000e+01, 3.90000000e+01,
       1.60000000e+01, 5.00000000e+00, 1.40000000e+01, 3.00000000e+00,
       4.80000000e+01, 1.10000000e+01, 3.20000000e+01, 4.70000000e+01,
       2.00000000e+00, 4.60000000e+01, 2.10000000e+01, 4.70000000e+01,
       1.80000000e+01, 2.60000000e+01, 9.00000000e+00, 2.40000000e+01,
       2.20000000e+01, 4.30000000e+01, 3.00000000e+00, 4.70000000e+01,
       2.60000000e+01, 3.55271368e-14, 1.10000000e+01, 5.00000000e+00,
       1.60000000e+01, 1.10000000e+01, 2.30000000e+01, 3.55271368e-14,
       3.10000000e+01, 4.90000000e+01, 4.30000000e+01, 2.20000000e+01,
       3.10000000e+01, 2.60000000e+01, 4.70000000e+01, 2.10000000e+01,
       2.20000000e+01, 3.90000000e+01, 1.50000000e+01, 8.00000000e+00,
      

In [ ]:
val_row_labels

array([45, 25,  0, 33, 14,  7, 46, 22, 10, 31,  5, 21,  1,  8, 26, 39, 16,
        5, 14,  3, 48, 11, 32, 47,  2, 46, 21, 47, 18, 26,  9, 24, 22, 43,
        3, 47, 26,  0, 11,  5, 16, 11, 23,  0, 31, 49, 43, 22, 31, 26, 47,
       21, 22, 39, 15,  8,  6, 48, 21, 46, 20, 29,  9, 19, 17, 26, 18, 28,
       18, 49, 36, 20, 21, 15, 18, 31, 37, 36, 10, 24,  2, 18, 35, 11, 27,
       18, 13, 42, 38,  5, 47, 43, 37, 43,  1, 47,  3, 34, 25, 14, 22,  6,
       43, 30, 11, 18, 16, 18, 31, 29,  9, 36, 15, 20, 30,  5, 21,  9,  2,
        5, 25, 35, 30, 47,  8, 40,  8, 40, 24, 47, 35,  0,  5, 41, 31, 15,
       25, 12,  5, 43, 21, 12, 18, 17,  0, 35, 19,  3, 29,  5, 11,  2, 33,
       37,  3, 20, 18, 13,  2, 19,  5, 44, 26, 23, 29, 38, 21, 21, 33,  5,
       29, 12, 37, 33, 35, 43, 12,  1,  7, 19, 21, 48, 47, 38, 22, 28,  1,
       40,  1, 47, 21,  1, 21, 21, 10, 41, 12, 15, 43, 29])

In [ ]:
print("Row model has a a Score: ", row_model.score(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model.score(val_row_entries, val_row_labels))

Row model has a a Score:  1.0
Row model has a a Score:  1.0


##For Columns

In [ ]:
train_col_entries, val_col_entries, train_col_labels, val_col_labels = tts(col_feat, final_labels[:, 0], test_size = 0.2,shuffle=False)

In [ ]:
from sklearn.linear_model import LinearRegression
col_model = LinearRegression()
col_model.fit(train_col_entries, train_col_labels)

LinearRegression()

In [ ]:
train_col_labels.shape, train_col_entries.shape

((800,), (800, 1000))

In [ ]:
val_col_entries.shape, val_col_labels.shape

((200, 1000), (200,))

In [ ]:
#Predict the response for test dataset
y_pred_col = col_model.predict(val_col_entries)
y_pred_col

array([ 1.04993803e+01,  4.83611987e+00,  9.00000000e+00,  1.64702201e+01,
        2.00000000e+00,  2.54427142e+00,  7.00000000e+00,  2.00000000e+00,
        8.40902954e+00,  7.00000000e+00, -4.96433984e-01,  1.80000000e+01,
        9.47540176e+00,  2.07243156e+01,  1.49774466e+01,  2.00000000e+00,
        6.00000000e+00,  9.62692407e+00,  7.10542736e-15,  4.23076089e+01,
        3.00000000e+00,  1.10000000e+01,  1.50000000e+01,  6.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.50000000e+01,  4.00000000e+00,
        1.50000000e+01,  1.40000000e+01,  1.80000000e+01,  1.30000000e+01,
        1.50000000e+01,  8.00000000e+00,  1.20000000e+01,  1.04993803e+01,
        1.44416515e+01,  2.50929742e+01,  1.77022369e+01,  3.00000000e+00,
        1.38814014e+01,  5.00000000e+00,  4.65032116e+00,  1.30000000e+01,
        7.00000000e+00,  1.04993803e+01,  1.04993803e+01,  1.01178990e+01,
        1.20000000e+01,  1.25361327e+01,  1.04993803e+01,  5.00000000e+00,
        2.23703742e+01,  

In [ ]:
val_col_labels

array([10,  9,  9,  5,  2, 12,  7,  2,  1,  7, 19, 18,  7,  6, 19,  2,  6,
        8,  0, 17,  3, 11, 15,  6,  1,  1, 15,  4, 15, 14, 18, 13, 15,  8,
       12,  0, 18,  1, 19,  3, 13,  5, 14, 13,  7, 10,  5,  9, 12,  1, 10,
        5, 12,  0, 11, 13, 18,  6,  6, 17, 14,  8,  4, 18, 15,  4,  6, 17,
       10,  5, 19, 10, 13,  5,  0,  7,  4,  7,  7, 11, 11, 13, 17,  4,  6,
        2,  0, 17,  8,  9,  1,  4,  1, 17,  2,  5,  4, 15,  1,  1,  6,  3,
        0,  8, 13, 11, 19,  0, 13,  3, 13, 15, 14, 15, 16,  5,  8, 16, 12,
        0,  2,  2, 16,  2,  0, 16, 13,  6, 13,  0, 12,  7,  6,  8,  8, 16,
        9, 16,  2,  2,  2,  8,  8, 14, 10, 19, 15,  0, 19, 11,  1, 13,  9,
        2,  3, 14,  4,  9,  4, 10,  7,  7, 16,  0, 10, 10,  5, 10,  9, 18,
        6, 15, 16,  8, 19, 10,  5,  5,  7, 14, 17,  5, 18,  4,  3,  4,  3,
        4,  7, 12,  3,  3,  5,  5, 15,  2, 11, 15, 18,  2])

In [ ]:
print("Col model has a a Score: ", col_model.score(train_col_entries, train_col_labels))
print("Col model has a a Score: ", col_model.score(val_col_entries, val_col_labels))

Col model has a a Score:  1.0
Col model has a a Score:  -0.2938062486755355


# Random Forest

## For Row

In [ ]:
from sklearn.ensemble import RandomForestClassifier
row_model = RandomForestClassifier()
row_model.fit(train_row_entries, train_row_labels)

RandomForestClassifier()

In [ ]:
#Predict the response for test dataset
y_pred_row = row_model.predict(val_row_entries)
y_pred_row

array([45, 25,  0, 33, 14,  7, 46, 22, 10, 31,  5, 21,  1,  8, 26, 39, 16,
        5, 14,  3, 48, 11, 32, 47,  2, 46, 21, 47, 18, 26,  9, 24, 22, 43,
        3, 47, 26,  0, 11,  5, 16, 11, 23,  0, 31, 49, 43, 22, 31, 26, 47,
       21, 22, 39, 15,  8,  6, 48, 21, 46, 20, 29,  9, 19, 17, 26, 18, 28,
       18, 49, 36, 20, 21, 15, 18, 31, 37, 36, 10, 24,  2, 18, 35, 11, 27,
       18, 13, 42, 38,  5, 47, 43, 37, 43,  1, 47,  3, 34, 25, 14, 22,  6,
       43, 30, 11, 18, 16, 18, 31, 29,  9, 36, 15, 20, 30,  5, 21,  9,  2,
        5, 25, 35, 30, 47,  8, 40,  8, 40, 24, 47, 35,  0,  5, 41, 31, 15,
       25, 12,  5, 43, 21, 12, 18, 17,  0, 35, 19,  3, 29,  5, 11,  2, 33,
       37,  3, 20, 18, 13,  2, 19,  5, 44, 26, 23, 29, 38, 21, 21, 33,  5,
       29, 12, 37, 33, 35, 43, 12,  1,  7, 19, 21, 48, 47, 38, 22, 28,  1,
       40,  1, 47, 21,  1, 21, 21, 10, 41, 12, 15, 43, 29])

In [ ]:
val_row_labels

array([45, 25,  0, 33, 14,  7, 46, 22, 10, 31,  5, 21,  1,  8, 26, 39, 16,
        5, 14,  3, 48, 11, 32, 47,  2, 46, 21, 47, 18, 26,  9, 24, 22, 43,
        3, 47, 26,  0, 11,  5, 16, 11, 23,  0, 31, 49, 43, 22, 31, 26, 47,
       21, 22, 39, 15,  8,  6, 48, 21, 46, 20, 29,  9, 19, 17, 26, 18, 28,
       18, 49, 36, 20, 21, 15, 18, 31, 37, 36, 10, 24,  2, 18, 35, 11, 27,
       18, 13, 42, 38,  5, 47, 43, 37, 43,  1, 47,  3, 34, 25, 14, 22,  6,
       43, 30, 11, 18, 16, 18, 31, 29,  9, 36, 15, 20, 30,  5, 21,  9,  2,
        5, 25, 35, 30, 47,  8, 40,  8, 40, 24, 47, 35,  0,  5, 41, 31, 15,
       25, 12,  5, 43, 21, 12, 18, 17,  0, 35, 19,  3, 29,  5, 11,  2, 33,
       37,  3, 20, 18, 13,  2, 19,  5, 44, 26, 23, 29, 38, 21, 21, 33,  5,
       29, 12, 37, 33, 35, 43, 12,  1,  7, 19, 21, 48, 47, 38, 22, 28,  1,
       40,  1, 47, 21,  1, 21, 21, 10, 41, 12, 15, 43, 29])

In [ ]:
print("Row model has a a Score: ", row_model.score(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model.score(val_row_entries, val_row_labels))

Row model has a a Score:  1.0
Row model has a a Score:  1.0


## For Columns

In [ ]:
col_model = RandomForestClassifier()
col_model.fit(train_col_entries, train_col_labels)

RandomForestClassifier()

In [ ]:
#Predict the response for test dataset
y_pred_col = col_model.predict(val_col_entries)
y_pred_col

array([ 0,  0,  9,  0,  2,  0,  7,  2,  0,  7,  0, 18,  0,  0,  0,  2,  6,
        0,  0,  0,  3, 11, 15,  6,  1,  1, 15,  4, 15, 14, 18, 13, 15,  8,
       12,  0,  0,  0,  0,  3,  0,  5,  0, 13,  7,  0,  0,  0, 12,  0,  0,
        5,  0,  0, 11,  0,  0,  6,  6,  0,  0,  8,  0, 18, 15,  0,  6,  0,
       10,  5,  0, 10,  0,  5,  0,  7,  4,  0,  7, 11, 11, 13,  0,  4,  6,
        2,  0, 17,  0,  0,  1,  4,  1, 17,  2,  0,  4, 15,  0,  1,  6,  3,
        0,  8,  0, 11,  0,  0,  0,  3, 13,  0,  0, 15, 16,  5,  8, 16,  0,
        0,  0,  0, 16,  0,  0,  0,  0,  6, 13,  0,  0,  7,  0,  0,  8, 16,
        0, 16,  0,  0,  2,  8,  0,  0, 10, 19,  0,  0,  0,  0,  1, 13,  0,
        0,  3,  0,  4,  0,  0,  0,  7,  0, 16,  0,  0,  0,  5, 10,  0,  0,
        0, 15, 16,  8, 19,  0,  0,  0,  7, 14, 17,  0, 18,  0,  3,  4,  3,
        4,  0, 12,  3,  3,  5,  5, 15,  2,  0, 15, 18,  0])

In [ ]:
val_col_labels

array([10,  9,  9,  5,  2, 12,  7,  2,  1,  7, 19, 18,  7,  6, 19,  2,  6,
        8,  0, 17,  3, 11, 15,  6,  1,  1, 15,  4, 15, 14, 18, 13, 15,  8,
       12,  0, 18,  1, 19,  3, 13,  5, 14, 13,  7, 10,  5,  9, 12,  1, 10,
        5, 12,  0, 11, 13, 18,  6,  6, 17, 14,  8,  4, 18, 15,  4,  6, 17,
       10,  5, 19, 10, 13,  5,  0,  7,  4,  7,  7, 11, 11, 13, 17,  4,  6,
        2,  0, 17,  8,  9,  1,  4,  1, 17,  2,  5,  4, 15,  1,  1,  6,  3,
        0,  8, 13, 11, 19,  0, 13,  3, 13, 15, 14, 15, 16,  5,  8, 16, 12,
        0,  2,  2, 16,  2,  0, 16, 13,  6, 13,  0, 12,  7,  6,  8,  8, 16,
        9, 16,  2,  2,  2,  8,  8, 14, 10, 19, 15,  0, 19, 11,  1, 13,  9,
        2,  3, 14,  4,  9,  4, 10,  7,  7, 16,  0, 10, 10,  5, 10,  9, 18,
        6, 15, 16,  8, 19, 10,  5,  5,  7, 14, 17,  5, 18,  4,  3,  4,  3,
        4,  7, 12,  3,  3,  5,  5, 15,  2, 11, 15, 18,  2])

In [ ]:
print("Col model has a a Score: ", col_model.score(train_col_entries, train_col_labels))
print("Col model has a a Score: ", col_model.score(val_col_entries, val_col_labels))

Col model has a a Score:  1.0
Col model has a a Score:  0.605


In [ ]:
train_rows = train_labels[:, 1]
train_cols = train_labels[:, 0]

In [ ]:
val_rows = val_labels[:, 1]
val_cols = val_labels[:, 0]

# SVM

## For Row

In [ ]:
from sklearn import svm

#Create a svm Classifier
row_model = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets For Row
row_model.fit(train_row_entries, train_row_labels)

#Predict the response for test dataset
y_pred_row = row_model.predict(val_row_entries)
y_pred_row

array([45, 25,  0, 33, 14,  7, 46, 22, 10, 31,  5, 21,  1,  8, 26, 39, 16,
        5, 14,  3, 48, 11, 32, 47,  2, 46, 21, 47, 18, 26,  9, 24, 22, 43,
        3, 47, 26,  0, 11,  5, 16, 11, 23,  0, 31, 49, 43, 22, 31, 26, 47,
       21, 22, 39, 15,  8,  6, 48, 21, 46, 20, 29,  9, 19, 17, 26, 18, 28,
       18, 49, 36, 20, 21, 15, 18, 31, 37, 36, 10, 24,  2, 18, 35, 11, 27,
       18, 13, 42, 38,  5, 47, 43, 37, 43,  1, 47,  3, 34, 25, 14, 22,  6,
       43, 30, 11, 18, 16, 18, 31, 29,  9, 36, 15, 20, 30,  5, 21,  9,  2,
        5, 25, 35, 30, 47,  8, 40,  8, 40, 24, 47, 35,  0,  5, 41, 31, 15,
       25, 12,  5, 43, 21, 12, 18, 17,  0, 35, 19,  3, 29,  5, 11,  2, 33,
       37,  3, 20, 18, 13,  2, 19,  5, 44, 26, 23, 29, 38, 21, 21, 33,  5,
       29, 12, 37, 33, 35, 43, 12,  1,  7, 19, 21, 48, 47, 38, 22, 28,  1,
       40,  1, 47, 21,  1, 21, 21, 10, 41, 12, 15, 43, 29])

In [ ]:
val_row_labels

array([45, 25,  0, 33, 14,  7, 46, 22, 10, 31,  5, 21,  1,  8, 26, 39, 16,
        5, 14,  3, 48, 11, 32, 47,  2, 46, 21, 47, 18, 26,  9, 24, 22, 43,
        3, 47, 26,  0, 11,  5, 16, 11, 23,  0, 31, 49, 43, 22, 31, 26, 47,
       21, 22, 39, 15,  8,  6, 48, 21, 46, 20, 29,  9, 19, 17, 26, 18, 28,
       18, 49, 36, 20, 21, 15, 18, 31, 37, 36, 10, 24,  2, 18, 35, 11, 27,
       18, 13, 42, 38,  5, 47, 43, 37, 43,  1, 47,  3, 34, 25, 14, 22,  6,
       43, 30, 11, 18, 16, 18, 31, 29,  9, 36, 15, 20, 30,  5, 21,  9,  2,
        5, 25, 35, 30, 47,  8, 40,  8, 40, 24, 47, 35,  0,  5, 41, 31, 15,
       25, 12,  5, 43, 21, 12, 18, 17,  0, 35, 19,  3, 29,  5, 11,  2, 33,
       37,  3, 20, 18, 13,  2, 19,  5, 44, 26, 23, 29, 38, 21, 21, 33,  5,
       29, 12, 37, 33, 35, 43, 12,  1,  7, 19, 21, 48, 47, 38, 22, 28,  1,
       40,  1, 47, 21,  1, 21, 21, 10, 41, 12, 15, 43, 29])

In [ ]:
print("Row model has a a Score: ", row_model.score(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model.score(val_row_entries, val_row_labels))

Row model has a a Score:  1.0
Row model has a a Score:  1.0


## For columns

In [ ]:
from sklearn import svm

#Create a svm Classifier
col_model = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets For col
col_model.fit(train_col_entries, train_col_labels)

#Predict the response for test dataset
y_pred_col = col_model.predict(val_col_entries)
y_pred_col

array([16, 16,  9, 16,  2, 16,  7,  2, 16,  7, 16, 18, 16, 16, 16,  2,  6,
       16,  0, 16,  3, 11, 15,  6,  1,  1, 15,  4, 15, 14, 18, 13, 15,  8,
       12, 16, 16, 16, 16,  3, 16,  5, 16, 13,  7, 16, 16, 16, 12, 16, 16,
        5, 16,  0, 11, 16, 16,  6,  6, 16, 16,  8, 16, 18, 15, 16,  6, 16,
       10,  5, 16, 10, 16,  5, 16,  7,  4, 16,  7, 11, 11, 13, 16,  4,  6,
        2,  0, 17, 16, 16,  1,  4,  1, 17,  2, 16,  4, 15, 16,  1,  6,  3,
       16,  8, 16, 11, 16, 16, 16,  3, 13, 16, 16, 15, 16,  5,  8, 16, 16,
        0, 16, 16, 16, 16,  0, 16, 16,  6, 13, 16, 16,  7, 16, 16,  8, 16,
       16, 16, 16, 16,  2,  8, 16, 16, 10, 19, 16,  0, 16, 16,  1, 13, 16,
       16,  3, 16,  4, 16, 16, 16,  7, 16, 16,  0, 16, 16,  5, 10, 16, 16,
       16, 15, 16,  8, 19, 16, 16, 16,  7, 14, 17, 16, 18, 16,  3,  4,  3,
        4, 16, 12,  3,  3,  5,  5, 15,  2, 16, 15, 18, 16])

In [ ]:
val_col_labels

array([10,  9,  9,  5,  2, 12,  7,  2,  1,  7, 19, 18,  7,  6, 19,  2,  6,
        8,  0, 17,  3, 11, 15,  6,  1,  1, 15,  4, 15, 14, 18, 13, 15,  8,
       12,  0, 18,  1, 19,  3, 13,  5, 14, 13,  7, 10,  5,  9, 12,  1, 10,
        5, 12,  0, 11, 13, 18,  6,  6, 17, 14,  8,  4, 18, 15,  4,  6, 17,
       10,  5, 19, 10, 13,  5,  0,  7,  4,  7,  7, 11, 11, 13, 17,  4,  6,
        2,  0, 17,  8,  9,  1,  4,  1, 17,  2,  5,  4, 15,  1,  1,  6,  3,
        0,  8, 13, 11, 19,  0, 13,  3, 13, 15, 14, 15, 16,  5,  8, 16, 12,
        0,  2,  2, 16,  2,  0, 16, 13,  6, 13,  0, 12,  7,  6,  8,  8, 16,
        9, 16,  2,  2,  2,  8,  8, 14, 10, 19, 15,  0, 19, 11,  1, 13,  9,
        2,  3, 14,  4,  9,  4, 10,  7,  7, 16,  0, 10, 10,  5, 10,  9, 18,
        6, 15, 16,  8, 19, 10,  5,  5,  7, 14, 17,  5, 18,  4,  3,  4,  3,
        4,  7, 12,  3,  3,  5,  5, 15,  2, 11, 15, 18,  2])

In [ ]:
print("col model has a a Score: ", col_model.score(train_col_entries, train_col_labels))
print("col model has a a Score: ", col_model.score(val_col_entries, val_col_labels))

col model has a a Score:  1.0
col model has a a Score:  0.585


# KNN

## For Row

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

row_model = KNeighborsClassifier(n_neighbors=1)

# Train the model using the training sets
row_model.fit(train_row_entries, train_row_labels)

#Predict Output
predicted= row_model.predict(val_row_entries) 
print(predicted)

[45 25  0 33 14  7 46 22 10 31  5 21  1  8 26 39 16  5 14  3 48 11 32 47
  2 46 21 47 18 26  9 24 22 43  3 47 26  0 11  5 16 11 23  0 31 49 43 22
 31 26 47 21 22 39 15  8  6 48 21 46 20 29  9 19 17 26 18 28 18 49 36 20
 21 15 18 31 37 36 10 24  2 18 35 11 27 18 13 42 38  5 47 43 37 43  1 47
  3 34 25 14 22  6 43 30 11 18 16 18 31 29  9 36 15 20 30  5 21  9  2  5
 25 35 30 47  8 40  8 40 24 47 35  0  5 41 31 15 25 12  5 43 21 12 18 17
  0 35 19  3 29  5 11  2 33 37  3 20 18 13  2 19  5 44 26 23 29 38 21 21
 33  5 29 12 37 33 35 43 12  1  7 19 21 48 47 38 22 28  1 40  1 47 21  1
 21 21 10 41 12 15 43 29]


In [ ]:
print("Row model has a a Score: ", row_model.score(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model.score(val_row_entries, val_row_labels))

Row model has a a Score:  1.0
Row model has a a Score:  1.0


## For Columns

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

col_model = KNeighborsClassifier(n_neighbors=1)

# Train the model using the training sets
col_model.fit(train_col_entries, train_col_labels)

#Predict Output
predicted= col_model.predict(val_col_entries) 
print(predicted)

[ 7  7  9  7  2  7  7  2  7  7  7 18  7  7  7  2  6  7  0  7  3 11 15  6
  1  1 15  4 15 14 18 13 15  8 12  7  7  7  7  3  7  5  7 13  7  7  7  7
 12  7  7  5  7  0 11  7  7  6  6  7  7  8  7 18 15  7  6  7 10  5  7 10
  7  5  7  7  4  7  7 11 11 13  7  4  6  2  0 17  7  7  1  4  1 17  2  7
  4 15  7  1  6  3  7  8  7 11  7  7  7  3 13  7  7 15 16  5  8 16  7  0
  7  7 16  7  0  7  7  6 13  7  7  7  7  7  8 16  7 16  7  7  2  8  7  7
 10 19  7  0  7  7  1 13  7  7  3  7  4  7  7  7  7  7 16  0  7  7  5 10
  7  7  7 15 16  8 19  7  7  7  7 14 17  7 18  7  3  4  3  4  7 12  3  3
  5  5 15  2  7 15 18  7]


In [ ]:
print("Col model has a a Score: ", col_model.score(train_col_entries, train_col_labels))
print("Col model has a a Score: ", col_model.score(val_col_entries, val_col_labels))

Col model has a a Score:  1.0
Col model has a a Score:  0.6


#ANN and CNN

## For Row

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#ann
row_model_ann = models.Sequential([
        layers.Dense(500, activation='relu'),
        layers.Dense(200, activation='relu'),
        layers.Dense(sz//rlen, activation='softmax')    
    ])

row_model_ann.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

row_model_ann.fit(train_row_entries, train_row_labels, epochs=20)

Epoch 1/20
25/25 [==============================] - 0s 3ms/step - loss: 3.6624 - accuracy: 0.6450
Epoch 2/20
25/25 [==============================] - 0s 3ms/step - loss: 2.6746 - accuracy: 0.9875
Epoch 3/20
25/25 [==============================] - 0s 3ms/step - loss: 1.0599 - accuracy: 0.9950
Epoch 4/20
25/25 [==============================] - 0s 3ms/step - loss: 0.1687 - accuracy: 1.0000
Epoch 5/20
25/25 [==============================] - 0s 3ms/step - loss: 0.0381 - accuracy: 1.0000
Epoch 6/20
25/25 [==============================] - 0s 4ms/step - loss: 0.0195 - accuracy: 1.0000
Epoch 7/20
25/25 [==============================] - 0s 3ms/step - loss: 0.0133 - accuracy: 1.0000
Epoch 8/20
25/25 [==============================] - 0s 4ms/step - loss: 0.0099 - accuracy: 1.0000
Epoch 9/20
25/25 [==============================] - 0s 3ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 10/20
25/25 [==============================] - 0s 3ms/step - loss: 0.0063 - accuracy: 1.0000
Epoch 11/20
25/25 [

In [ ]:
row_model_ann.evaluate(val_row_entries, val_row_labels)

7/7 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000


[0.0016727496404200792, 1.0]

In [ ]:
print("Row model has a a Score: ", row_model_ann.evaluate(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model_ann.evaluate(val_row_entries, val_row_labels))

25/25 [==============================] - 0s 2ms/step - loss: 0.0016 - accuracy: 1.0000
Row model has a a Score:  [0.0016195472562685609, 1.0]
7/7 [==============================] - 0s 2ms/step - loss: 0.0017 - accuracy: 1.0000
Row model has a a Score:  [0.0016727496404200792, 1.0]


In [ ]:
#CNN

In [ ]:
row_model_cnn = models.Sequential([
    layers.Dense(64, activation='relu'),
    layers.Dense(sz//rlen, activation='softmax')
])

In [ ]:
row_model_cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
row_model_cnn.fit(train_row_entries, train_row_labels, epochs=10)

Epoch 1/10
25/25 [==============================] - 0s 2ms/step - loss: 3.8680 - accuracy: 0.0750
Epoch 2/10
25/25 [==============================] - 0s 2ms/step - loss: 3.7263 - accuracy: 0.4175
Epoch 3/10
25/25 [==============================] - 0s 2ms/step - loss: 3.5650 - accuracy: 0.7138
Epoch 4/10
25/25 [==============================] - 0s 2ms/step - loss: 3.3675 - accuracy: 0.9137
Epoch 5/10
25/25 [==============================] - 0s 2ms/step - loss: 3.1190 - accuracy: 0.9625
Epoch 6/10
25/25 [==============================] - 0s 2ms/step - loss: 2.8187 - accuracy: 0.9862
Epoch 7/10
25/25 [==============================] - 0s 2ms/step - loss: 2.4683 - accuracy: 0.9937
Epoch 8/10
25/25 [==============================] - 0s 2ms/step - loss: 2.0859 - accuracy: 1.0000
Epoch 9/10
25/25 [==============================] - 0s 1ms/step - loss: 1.6902 - accuracy: 1.0000
Epoch 10/10
25/25 [==============================] - 0s 2ms/step - loss: 1.3146 - accuracy: 1.0000


In [ ]:
print("Row model has a a Score: ", row_model_cnn.evaluate(train_row_entries, train_row_labels))
print("Row model has a a Score: ", row_model_cnn.evaluate(val_row_entries, val_row_labels))

25/25 [==============================] - 0s 1ms/step - loss: 1.1281 - accuracy: 1.0000
Row model has a a Score:  [1.1280527114868164, 1.0]
7/7 [==============================] - 0s 3ms/step - loss: 1.1829 - accuracy: 1.0000
Row model has a a Score:  [1.1828750371932983, 1.0]


## For Column

In [ ]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
#ann
col_model_ann = models.Sequential([
        layers.Dense(500, activation='relu'),
        layers.Dense(200, activation='relu'),
        layers.Dense(rlen-1, activation='softmax')    
    ])

col_model_ann.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

col_model_ann.fit(train_col_entries, train_col_labels, epochs=20)

Epoch 1/20
25/25 [==============================] - 1s 7ms/step - loss: 2.9833 - accuracy: 0.1125
Epoch 2/20
25/25 [==============================] - 0s 7ms/step - loss: 2.8659 - accuracy: 0.4425
Epoch 3/20
25/25 [==============================] - 0s 6ms/step - loss: 2.6159 - accuracy: 0.7075
Epoch 4/20
25/25 [==============================] - 0s 6ms/step - loss: 2.0385 - accuracy: 0.9337
Epoch 5/20
25/25 [==============================] - 0s 7ms/step - loss: 1.1083 - accuracy: 0.9975
Epoch 6/20
25/25 [==============================] - 0s 6ms/step - loss: 0.3662 - accuracy: 1.0000
Epoch 7/20
25/25 [==============================] - 0s 6ms/step - loss: 0.0999 - accuracy: 1.0000
Epoch 8/20
25/25 [==============================] - 0s 6ms/step - loss: 0.0393 - accuracy: 1.0000
Epoch 9/20
25/25 [==============================] - 0s 6ms/step - loss: 0.0229 - accuracy: 1.0000
Epoch 10/20
25/25 [==============================] - 0s 6ms/step - loss: 0.0157 - accuracy: 1.0000
Epoch 11/20
25/25 [

In [ ]:
col_model_ann.evaluate(val_col_entries, val_col_labels)

7/7 [==============================] - 0s 3ms/step - loss: 1.3450 - accuracy: 0.6000


[1.3449914455413818, 0.6000000238418579]

In [ ]:
print("col model has a a Score: ", col_model_ann.evaluate(train_col_entries, train_col_labels))
print("col model has a a Score: ", col_model_ann.evaluate(val_col_entries, val_col_labels))

25/25 [==============================] - 0s 3ms/step - loss: 0.0023 - accuracy: 1.0000
col model has a a Score:  [0.0022856821306049824, 1.0]
7/7 [==============================] - 0s 3ms/step - loss: 1.3450 - accuracy: 0.6000
col model has a a Score:  [1.3449914455413818, 0.6000000238418579]


In [ ]:
#CNN

In [ ]:
col_model_cnn = models.Sequential([
    layers.Dense(64, activation='relu'),
    layers.Dense(rlen-1, activation='softmax')
])

In [ ]:
col_model_cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
col_model_cnn.fit(train_col_entries, train_col_labels, epochs=10)

Epoch 1/10
25/25 [==============================] - 0s 2ms/step - loss: 2.9930 - accuracy: 0.0613
Epoch 2/10
25/25 [==============================] - 0s 3ms/step - loss: 2.9630 - accuracy: 0.1775
Epoch 3/10
25/25 [==============================] - 0s 3ms/step - loss: 2.9320 - accuracy: 0.2975
Epoch 4/10
25/25 [==============================] - 0s 2ms/step - loss: 2.8937 - accuracy: 0.4050
Epoch 5/10
25/25 [==============================] - 0s 2ms/step - loss: 2.8465 - accuracy: 0.5500
Epoch 6/10
25/25 [==============================] - 0s 2ms/step - loss: 2.7848 - accuracy: 0.6275
Epoch 7/10
25/25 [==============================] - 0s 2ms/step - loss: 2.7055 - accuracy: 0.7075
Epoch 8/10
25/25 [==============================] - 0s 2ms/step - loss: 2.6036 - accuracy: 0.7875
Epoch 9/10
25/25 [==============================] - 0s 2ms/step - loss: 2.4744 - accuracy: 0.8562
Epoch 10/10
25/25 [==============================] - 0s 2ms/step - loss: 2.3145 - accuracy: 0.9337


In [ ]:
col_model_cnn.evaluate(val_col_entries, val_col_labels)

7/7 [==============================] - 0s 2ms/step - loss: 2.5882 - accuracy: 0.5800


[2.5882151126861572, 0.5799999833106995]

In [ ]:
print("col model has a a Score: ",col_model_cnn.evaluate(train_col_entries, train_col_labels))
print("col model has a a Score: ", col_model_cnn.evaluate(val_col_entries, val_col_labels))

25/25 [==============================] - 0s 2ms/step - loss: 2.2016 - accuracy: 0.9663
col model has a a Score:  [2.2016491889953613, 0.9662500023841858]
7/7 [==============================] - 0s 2ms/step - loss: 2.5882 - accuracy: 0.5800
col model has a a Score:  [2.5882151126861572, 0.5799999833106995]


#(Data contain row and col both)

## Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
row_model = LinearRegression()
row_model.fit(train_entries, train_rows)

LinearRegression()

In [ ]:
col_model = LinearRegression()
col_model.fit(train_entries, train_cols)

LinearRegression()

In [ ]:
print("Row model has a a Score: ", row_model.score(train_entries, train_rows))
print("Col model has a b Score: ",col_model.score(train_entries, train_cols))

Row model has a a Score:  1.0
Col model has a b Score:  1.0


In [ ]:
print("Row model has a a Score: ", row_model.score(val_entries, val_rows))
print("Col model has a b Score: ",col_model.score(val_entries, val_cols))

Row model has a a Score:  0.9850451456975633
Col model has a b Score:  0.4445099132842445


## Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge
row_model = Ridge()
row_model.fit(train_entries, train_rows)

Ridge()

In [ ]:
col_model = Ridge()
col_model.fit(train_entries, train_cols)

Ridge()

In [ ]:
'''
Return the coefficient of determination of the prediction.

The coefficient of determination  is defined as 

, where  is the residual sum of squares ((y_true - y_pred)** 2).sum() and  is the total sum of squares ((y_true - y_true.mean()) ** 2).sum(). 
The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). 
A constant model that always predicts the expected value of y, disregarding the input features, would get a  score of 0.0.

'''

'\nReturn the coefficient of determination of the prediction.\n\nThe coefficient of determination  is defined as \n\n, where  is the residual sum of squares ((y_true - y_pred)** 2).sum() and  is the total sum of squares ((y_true - y_true.mean()) ** 2).sum(). \nThe best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). \nA constant model that always predicts the expected value of y, disregarding the input features, would get a  score of 0.0.\n\n'

In [ ]:
print("Row model has a a Score: ", row_model.score(train_entries, train_rows))
print("Col model has a b Score: ",col_model.score(train_entries, train_cols))

Row model has a a Score:  0.9965445619290669
Col model has a b Score:  0.83928402622763


In [ ]:
print("Row model has a a Score: ", row_model.score(val_entries, val_rows))
print("Col model has a b Score: ",col_model.score(val_entries, val_cols))

Row model has a a Score:  0.9876610737551275
Col model has a b Score:  0.41383302521267507


## Random Forest Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
row_model = RandomForestRegressor()
row_model.fit(train_entries, train_rows)

RandomForestRegressor()

In [ ]:
col_model = RandomForestRegressor()
col_model.fit(train_entries, train_cols)

RandomForestRegressor()

In [ ]:
print("Row model has a a Score: ", row_model.score(train_entries, train_rows))
print("Col model has a b Score: ",col_model.score(train_entries, train_cols))

Row model has a a Score:  1.0
Col model has a b Score:  0.9122062358378433


In [ ]:
print("Row model has a a Score: ", row_model.score(val_entries, val_rows))
print("Col model has a b Score: ",col_model.score(val_entries, val_cols))

Row model has a a Score:  1.0
Col model has a b Score:  0.47405348852113216
